### ISSUE TITLE
Visualization of the inter-cluster accessibility of top-20 clusters

### ISSUE THREAD

**Issue by curieuxjy** [zita-ch/K-Access#1]
Hi there,

Thank you for sharing your excellent research work. I was curious about how to create the inter-cluster accessibility plot for the top 20 clusters in your paper. I attempted to replicate this graph using [Pycircos](https://github.com/ponnhide/pyCircos), but unfortunately, I couldn't find any code to plot the circos graph in this repository, and I had difficulty understanding some variables required to draw it.

I have a few questions to ask you:

- Is there a specific criterion for **ordering the clusters' index**? It wasn't apparent to me if the clusters were ordered based on their size.

- How did you determine **the position of each sampled pose data on the axis of a circle**? Did you reorganize the pose samples in a direction that would display the continuous changes of poses?

Thank you in advance for your help!

**Comment by zita-ch** [comment]
Hi,
1. the indices are indeed ordered by the size
2. I did not reorganize the samples. The figure is created by (if I remember it correctly) the Chord library. I did not do any cherry-picking, and we don't care about the positions. It is a chord diagram, which means we only look at the chords. btw, if you find the samples not well (or meaningfully) separated, you can have more data (e.g. 4000 poses) and try again.

**Comment by curieuxjy** [comment]
Thank you so much!

I have an additional question. 

In your paper, I noticed that you initially sampled 2.4k poses and then later sampled 1000 poses. I'm curious to know the reason for resampling 1000 poses, and was this just a random selection of 1000 poses from the initial 2400? 
Also, I'm wondering why you didn't use all 2400 poses?

Thank you for taking the time to answer my questions!

**Comment by zita-ch** [comment]
coz I then was able to do the train/test split for the poses.

**Comment by curieuxjy** [comment]
I see. thanks
